name: pearl
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - colorama=0.4.6
  - libexpat=2.5.0
  - libffi=3.4.2
  - libsqlite=3.44.2
  - libzlib=1.2.13
  - openssl=3.2.0
  - pip=23.3.2
  - python=3.12.1
  - setuptools=69.0.3
  - tk=8.6.13
  - tqdm=4.66.1
  - tzdata=2023d
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wheel=0.42.0
  - xz=5.2.6
  - pip:
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - docutils==0.20.1
      - idna==3.6
      - install==1.3.5
      - kivy==2.3.0
      - kivy-deps-angle==0.4.0
      - kivy-deps-glew==0.3.1
      - kivy-deps-sdl2==0.7.0
      - kivy-garden==0.1.5
      - numpy==1.26.3
      - pillow==10.2.0
      - pygments==2.17.2
      - pypiwin32==223
      - pywin32==306
      - requests==2.31.0
      - urllib3==2.1.0
